kind: DSCInitialization
apiVersion: dscinitialization.opendatahub.io/v2
metadata:
  labels:
    app.kubernetes.io/name: dscinitialization
  name: default-dsci
spec:
  applicationsNamespace: opendatahub
  monitoring:
    managementState: Managed
    metrics: {}
    namespace: opendatahub
  trustedCABundle:
    customCABundle: ''
    managementState: Managed
